apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  labels:
      app: nginx
spec:
  containers:
  - name: pod-demo-container
    image: nginx:1.7.9
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
      preStop:
        exec:
          command: ["/usr/sbin/nginx","-s","quit"]
