kind: Pod
apiVersion: v1
metadata:
  name: pod-mount-pvc
spec:
  containers:
    - name: pod-name 
      image: nginx:1.7.9
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
