apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - host: myservices.com
    http:
      paths:
        - path: /backend
          backend:
            serviceName: webapp
            servicePort: 8080