---
apiVersion: v1
kind: ConfigMap
metadata:
    name: configmap-to-mount-a
data:
    index.html: |
        <HTML>
          <HEAD>
            <TITLE>Service A</TITLE>
          </HEAD>
          <BODY>
            <H>This is index of service a</H>
          </BODY>
        </HTML> 
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-a-pod
  labels:
      app: nginx-a
spec:
  containers:
    - name: test-container
      image: nginx:1.7.9
      volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx/conf.d
  volumes:
    - name: config-volume
      configMap:
        name: configmap-to-mount-a
---
apiVersion: v1
kind: Service
metadata:
    name: service-a
spec:
    ports:
    - port: 80
    selector:
        app: nginx-a
