---
apiVersion: v1
kind: ConfigMap
metadata:
    name: configmap-to-mount
data:
    nginx.conf: |
        server {
            listen       80;
            server_name  localhost;
            location ~* {
                proxy_pass https://www.baidu.com;
            }
        } 
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-for-configmap
  labels:
      app: nginx
spec:
  containers:
    - name: test-container
      image: nginx:1.7.9
      volumeMounts:
      - name: config-volume
        mountPath: /etc/nginx/conf.d
  volumes:
    - name: config-volume
      configMap:
        name: configmap-to-mount
---
apiVersion: v1
kind: Service
metadata:
    name: pod-for-configmap-service
spec:
    type: NodePort
    ports:
    - port: 80
      nodePort: 31234
    selector:
        app: nginx
